### ISSUE TITLE
Add refresh button to left panel when in house number mode

### ISSUE THREAD

**Issue by kbaumgart** [WazeDev/WME-GIS-Layers#44]
Since some info is only displayed at certain zoom levels, I find that i need to refresh the layers to get more info  while in house number mode. I am aware of Panel Swap, however it tends to cause problems for me. Having a way to refresh the GIS data while in house number mode could make things easier to work along a long stretch of road without having to save, refresh the data in the GIS-L tab, and then go back to HN mode.

**Comment by mapomatic** [comment]
I'm not sure I understand.  Generally, a GIS Layers refresh is only useful when there are new or updated layers available.  That should be a fairly infrequent event.  If you can provide examples or more detail, maybe that would help me understand.

**Comment by kbaumgart** [comment]
Basically, when panning the map I had been running into an issue wherein the request for the underlying GIS data wasn't being done, so i'd have to manually refresh the layers to do a new call. I haven't had the issue as much lately so I'm not sure if something changed with the script, with WME or with the underlying servers. I'll close this for the time being and if it comes back I'll reopen it with screenshots/video to show what I mean
