### ISSUE TITLE
Layer Restrictions

### ISSUE THREAD

**Issue by mythdraug-waze** [WazeDev/WME-GIS-Layers#46]
Can an option be added to restrict visibility of a layer based on Rank/Role/UserID?   I've found myself on more than one occasion experimenting with a layer prior to wanting to make it available.   Additionally, I've heard a request from local leadership to be able to review new layers for suitability.

**Comment by mapomatic** [comment]
Done

**Comment by mythdraug-waze** [comment]
🥇 Thanks!
