### ISSUE TITLE
Layer disclaimer - ToS Compliance

### ISSUE THREAD

**Issue by mythdraug-waze** [WazeDev/WME-GIS-Layers#47]
One datasource that I'm pursuing states that a disclaimer must be presented stating that "This uses data from _____ .   Data you see may be altered from the original source data.   Original source data may not be accurate.  ____ is not responsible for ____."    as part of their ToS. 

Would it be possible to codify display of a ToS statement when a layer is enabled from the script preferences?

**Comment by mapomatic** [comment]
Added "one time alert" feature.
