### ISSUE TITLE
Refresh all layers not working

### ISSUE THREAD

**Issue by SkulllzzCode** [WazeDev/WME-GIS-Layers#61]
when you press the refresh all layers button it logs 
![image](https://user-images.githubusercontent.com/15911542/132735279-949dc3c3-f0e2-4916-9577-cdb6d2063685.png)
and the button just keeps spinning until a full web page refresh

**Comment by mapomatic** [comment]
Thanks for the report.  If anyone wants to submit a pull request for a fix, I would appreciate it.  It may be a while before I get around to investigating.
